///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UserCodeApplication
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UserCodeApplicationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f6b112c9-367b-41e2-b7ba-2fb262f34f99")]
    public partial class UserCodeApplicationRepository : RepoGenBaseFolder
    {
        static UserCodeApplicationRepository instance = new UserCodeApplicationRepository();
        UserCodeApplicationRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the UserCodeApplicationRepository element repository.
        /// </summary>
        [RepositoryFolder("f6b112c9-367b-41e2-b7ba-2fb262f34f99")]
        public static UserCodeApplicationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UserCodeApplicationRepository() 
            : base("UserCodeApplicationRepository", "/", null, 0, false, "f6b112c9-367b-41e2-b7ba-2fb262f34f99", ".\\RepositoryImages\\UserCodeApplicationRepositoryf6b112c9.rximgres")
        {
            _applicationundertest = new UserCodeApplicationRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f6b112c9-367b-41e2-b7ba-2fb262f34f99")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3cba9d95-2bfd-4229-a38b-78e7df21556f")]
        public virtual UserCodeApplicationRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class UserCodeApplicationRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3cba9d95-2bfd-4229-a38b-78e7df21556f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            UserCodeApplicationRepositoryFolders.IntroductionPaneFolder _introductionpane;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "3cba9d95-2bfd-4229-a38b-78e7df21556f", "")
            {
                _introductionpane = new UserCodeApplicationRepositoryFolders.IntroductionPaneFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3cba9d95-2bfd-4229-a38b-78e7df21556f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3cba9d95-2bfd-4229-a38b-78e7df21556f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IntroductionPane folder.
            /// </summary>
            [RepositoryFolder("e5fcd6f0-c033-44a0-acd6-b1da742dd718")]
            public virtual UserCodeApplicationRepositoryFolders.IntroductionPaneFolder IntroductionPane
            {
                get { return _introductionpane; }
            }
        }

        /// <summary>
        /// The IntroductionPaneFolder folder.
        /// </summary>
        [RepositoryFolder("e5fcd6f0-c033-44a0-acd6-b1da742dd718")]
        public partial class IntroductionPaneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfieldnameInfo;
            RepoItemInfo _btnsubmitInfo;
            RepoItemInfo _btnresetInfo;
            RepoItemInfo _lblwelcomemsgInfo;

            /// <summary>
            /// Creates a new IntroductionPane  folder.
            /// </summary>
            public IntroductionPaneFolder(RepoGenBaseFolder parentFolder) :
                    base("IntroductionPane", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "e5fcd6f0-c033-44a0-acd6-b1da742dd718", "")
            {
                _txtfieldnameInfo = new RepoItemInfo(this, "TxtFieldName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "0786c3f4-7cae-4ee5-98a4-135409733494");
                _btnsubmitInfo = new RepoItemInfo(this, "BtnSubmit", "button[@controlname='btnSubmitUserName']", 30000, null, "8ed6b0dc-6add-4b39-8a10-4f1c305f227e");
                _btnresetInfo = new RepoItemInfo(this, "BtnReset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "bb095f79-99e0-4a0c-996d-d81ed38e0cf5");
                _lblwelcomemsgInfo = new RepoItemInfo(this, "LblWelcomeMsg", "text[@controlname='lblWelcomeMessage']", 30000, null, "b90b843c-4cb3-4f3b-99b0-835fcf74f2ba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e5fcd6f0-c033-44a0-acd6-b1da742dd718")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e5fcd6f0-c033-44a0-acd6-b1da742dd718")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtFieldName item.
            /// </summary>
            [RepositoryItem("0786c3f4-7cae-4ee5-98a4-135409733494")]
            public virtual Ranorex.Text TxtFieldName
            {
                get
                {
                    return _txtfieldnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFieldName item info.
            /// </summary>
            [RepositoryItemInfo("0786c3f4-7cae-4ee5-98a4-135409733494")]
            public virtual RepoItemInfo TxtFieldNameInfo
            {
                get
                {
                    return _txtfieldnameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmit item.
            /// </summary>
            [RepositoryItem("8ed6b0dc-6add-4b39-8a10-4f1c305f227e")]
            public virtual Ranorex.Button BtnSubmit
            {
                get
                {
                    return _btnsubmitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmit item info.
            /// </summary>
            [RepositoryItemInfo("8ed6b0dc-6add-4b39-8a10-4f1c305f227e")]
            public virtual RepoItemInfo BtnSubmitInfo
            {
                get
                {
                    return _btnsubmitInfo;
                }
            }

            /// <summary>
            /// The BtnReset item.
            /// </summary>
            [RepositoryItem("bb095f79-99e0-4a0c-996d-d81ed38e0cf5")]
            public virtual Ranorex.Link BtnReset
            {
                get
                {
                    return _btnresetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The BtnReset item info.
            /// </summary>
            [RepositoryItemInfo("bb095f79-99e0-4a0c-996d-d81ed38e0cf5")]
            public virtual RepoItemInfo BtnResetInfo
            {
                get
                {
                    return _btnresetInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMsg item.
            /// </summary>
            [RepositoryItem("b90b843c-4cb3-4f3b-99b0-835fcf74f2ba")]
            public virtual Ranorex.Text LblWelcomeMsg
            {
                get
                {
                    return _lblwelcomemsgInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMsg item info.
            /// </summary>
            [RepositoryItemInfo("b90b843c-4cb3-4f3b-99b0-835fcf74f2ba")]
            public virtual RepoItemInfo LblWelcomeMsgInfo
            {
                get
                {
                    return _lblwelcomemsgInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
